export const SHOW_MAP_INFOWINDOW = 'SHOW_MAP_INFOWINDOW';
export const SHOW_HEAT_LAYER = 'SHOW_HEAT_LAYER';
export const SHOW_MARKERS = 'SHOW_MARKERS';
export const SHOW_OUTBREAK_MARKERS = 'SHOW_OUTBREAK_MARKERS';
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS';
export const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE';
